### PR TITLE
Feature/fbsdk update

### PR DESCRIPTION
**Pull request by SyedImran9597**
updated firebase message version to 24.0.0 and removed the deprecated firebaseintanceId

### CODE REVIEW

**Comment by quinton-j** [comment]
@CangsuH , we discussed this PR is unnecessary and you were going to speak to @SyedImran9597 about closing it.  Has that discussion happened?

**Comment by CangsuH** [comment]
@quinton-j Yes, I did talk to @SyedImran9597 that there is no need for this PR. We should continue to use my forked branch until we can move up to the latest library.

@SyedImran9597 Please close this PR.

@justinghantous We should have a tech debt item to move up the latest [react-native-notifications](https://github.com/wix/react-native-notifications).

**Comment by SyedImran9597** [comment]
I will close that PR.

**Comment by quinton-j** [comment]
It's still open.  Plz close.

**Comment by SyedImran9597** [comment]
Its closed now.

**Comment by quinton-j** [comment]
Thx.  One further note, @SyedImran9597 .  Stop using email responds to comments and instead use the github UI.  Email responses add unnecessary junk that I've had to remove. 🚮

**Comment by SyedImran9597** [comment]
ok sure. I will do the same. Thank you

**Pull request closed without merging**
